name: Run Tests and Measure Coverage on PR

on:
  pull_request:
    branches:
      - main

env:
  TF_CLOUD_ORGANIZATION: "${{ secrets.TF_ORG_NAME }}"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "repo-creation"
  CONFIG_DIRECTORY: "./tf/"

jobs:
  ci-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pipenv"

      - name: Install dependencies
        run: make setup

      - name: Run tests with coverage
        run: make test

      - name: Report coverage with Codecov
        uses: codecov/codecov-action@v2

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
